baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Helamael Blog'
theme = 'holy'

[params] 
  copyright = "© 2024 Helamael"

[taxonomies]
games = "games"

[menu]
  [[menu.main]]
    identifier = "games"
    name = "games"
    url = "/games/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 2